task-6: make up desktop header for main page
yandex-practicum-14-8/projito_14_8 pull request #29
Opened 2022-07-14 16:25 UTC by vladislavkuc

Сверстал desktop header для main page

2022-07-15 13:10 UTC, MariaChernova requested changes

2022-07-15 13:10 UTC, MariaChernova commented on .editorconfig
> +
Что это за файл?

2022-07-15 13:10 UTC, MariaChernova commented on index.html
> +      <img src="./images/logo.png" alt="логотип проекта Прожито" class="header__logo">
Лучше заменить png на svg. Сейчас логотип размыт

2022-07-17 13:44 UTC, vladislavkuc commented on .editorconfig
> +
Конфиг плагина для VS Code вывалился, убрал

2022-07-17 13:44 UTC, vladislavkuc commented on index.html
> +      <img src="./images/logo.png" alt="логотип проекта Прожито" class="header__logo">
Заменил

2022-07-17 13:47 UTC, MariaChernova approved these changes

2022-07-17 13:47 UTC, merged