feat: десктоп Материалы
yandex-practicum-14-8/projito_14_8 pull request #30
Opened 2022-07-15 04:55 UTC by Ser2204

task-14 Десктоп Материалы

2022-07-15 09:04 UTC, MariaChernova requested changes

2022-07-15 09:04 UTC, MariaChernova commented on index.html
> +    <meta charset="UTF-8" />
Вижу, что ты поправил табуляцию. Спасибо, это я просмотрела. Когда буду делать мерж, твоя правильная табуляция будет в ветке main. Но у тегов <meta> и <link> нет закрывающих тегов. Т.е. слеш перед скобкой не нужен

2022-07-15 09:21 UTC, Ser2204 commented on index.html
> +            />
это pretir в vscode делает. Она там и стояла, а при сохранении vscode делает такую разметку. только отключив автопроверку могу изменить.

2022-07-15 09:22 UTC, Ser2204 commented on index.html
> +            </div>
похоже строка не дописана. что вместо пробела вставить?

2022-07-15 09:24 UTC, Ser2204 commented on index.html
> -</html>
это автоматом получилось. сам не удалял. почему-то был конфликт с веткой таск-24. и, видимо, resolved так сработал

2022-07-15 09:30 UTC, Ser2204 commented on index.html
> +            </div>
поменяю тег на абзац. иначе не знаю как сделать перенос в соответствии с брифом

2022-07-15 10:08 UTC, Ser2204 commented on index.html
> -</html>
честно говоря, хотелось бы понимать почему так получилось

2022-07-15 12:27 UTC, MariaChernova requested changes

2022-07-15 12:27 UTC, MariaChernova commented on blocks/diary/diary.css
> +.diary {
Добавь для карточки cursor: pointer; чтобы при наведении было видно, что по ней можно кликнуть

2022-07-15 12:27 UTC, MariaChernova commented on index.html
> +            />
У меня prettier тоже работает и такого нет. Вот [документация ](https://developer.mozilla.org/ru/docs/Web/HTML/Element/img)для img, [для meta](https://developer.mozilla.org/ru/docs/Web/HTML/Element/meta) и для [link](https://developer.mozilla.org/ru/docs/Web/HTML/Element/link)/ Так как эти  теги пустые, закрывающих тегов у них быть не может

2022-07-15 12:27 UTC, MariaChernova commented on index.html
> +            </div>
Перенос можно сделать с помощью br. Поставить его на место пробела и строка перенесется.

2022-07-15 12:27 UTC, MariaChernova commented on index.html
> -</html>
Скорее всего не ввел какие-то команды. Это сейчас не важно. Главное, оставь свою табуляцию и убери слеши ( / ) в конце тегов meta и link

2022-07-16 06:29 UTC, MariaChernova approved these changes

2022-07-16 07:52 UTC, MariaChernova requested changes

2022-07-16 07:52 UTC, MariaChernova commented on index.html
> +
Убери все пустые строки из html. Иначе код не будет валидным

2022-07-17 08:17 UTC, AlinaMalginova1998 approved these changes

2022-07-17 08:18 UTC, AlinaMalginova1998 commented on index.html
> +
Я думаю, на валидность код будем чекать уже в конце, когда весь паззл соберем :)

2022-07-17 12:19 UTC, MariaChernova approved these changes

2022-07-17 12:19 UTC, merged