Task 12 news
yandex-practicum-14-8/projito_14_8 pull request #40
Opened 2022-07-16 22:37 UTC by iVANECHKA

Оставил пока бежевую полосу прокрутки. Если слайдер всё-таки нам нужно будет реализовывать, то скролл придётся явно по-другому сделать.

2022-07-17 02:41 UTC, MariaChernova requested changes

2022-07-17 02:41 UTC, MariaChernova commented on blocks/page/page.css
> +  max-width: 1440px;
В ветке main сейчас нет максимальной ширины. Можешь увидеть, что у тебя конфликт в этом файле. Убирай это свойство и тогда блок будет занимать 100% от ширины экрана, как на макете.

2022-07-17 02:41 UTC, MariaChernova commented on blocks/news/__arrow-right/news__arrow-right.css
> +.news__arrow-right {
добавь на обе стрелки cursor: pointer. и hover. В UI ките это не прорисовано.  Мы везде до дефолту ставим непрозрачнсть 0.7, если в UI нет конкретных указаний

2022-07-17 02:41 UTC, MariaChernova commented on blocks/news/__card/news__card.css
> +}
В UI ките указано, что при наведении на весь этот элемент непрозрачность 80%

2022-07-17 02:41 UTC, MariaChernova commented on index.html
> +            <button class="news__arrow-left"></button>
Всем кнопкам обязательно присваивай type: button и alt

2022-07-17 02:41 UTC, MariaChernova commented on pages/index.css
> +@import url(../blocks/news/news.css);
Здесь конфликт. Замёржи себе в ветку origin/main и убери конфликт перед следующим ревью

2022-07-20 21:25 UTC, iVANECHKA commented on blocks/page/page.css
> +  max-width: 1440px;
Готово

2022-07-20 21:25 UTC, iVANECHKA commented on blocks/news/__arrow-right/news__arrow-right.css
> +.news__arrow-right {
готово

2022-07-20 21:26 UTC, iVANECHKA commented on blocks/news/__card/news__card.css
> +}
Готово

2022-07-20 21:26 UTC, iVANECHKA commented on pages/index.css
> +@import url(../blocks/news/news.css);
Готово

2022-07-21 20:02 UTC, MariaChernova approved these changes

2022-07-21 20:02 UTC, merged