Task 56
yandex-practicum-14-8/projito_14_8 pull request #64
Opened 2022-07-19 19:46 UTC by Ser2204

2022-07-20 08:24 UTC, MariaChernova requested changes

2022-07-20 08:24 UTC, MariaChernova commented on magazine.html
> +      <h1 class="title">Журнал «Прожито»</h1>
Если добавил заголовок, то пропиши ему правильные свойства, чтобы уже готово все было

2022-07-20 18:28 UTC, Ser2204 commented on magazine.html
> +      <h1 class="title">Журнал «Прожито»</h1>
Заголовок кто-то до меня добавил. Но, это ничего. Класс ему добавил. Проверь, пожалуйста

2022-07-21 20:00 UTC, MariaChernova approved these changes

2022-07-21 20:00 UTC, merged