task-32.раскрытый декстоп хедер
yandex-practicum-14-8/projito_14_8 pull request #70
Opened 2022-07-20 20:18 UTC by Ser2204

2022-07-23 11:07 UTC, AlinaMalginova1998 reviewed
Необходимо внести несколько изменений

2022-07-23 11:07 UTC, AlinaMalginova1998 commented on blocks/header/__link-down/header__link-down.css
> +  padding: 12px 10px 11px;
Из-за паддингов получается слишком большой промежуток между пунктами меню.
![image](https://user-images.githubusercontent.com/39488063/180602275-fa59726e-8b30-467e-a901-21f346cfa342.png)

2022-07-23 11:07 UTC, AlinaMalginova1998 commented on blocks/header/__link-down/header__link-down.css
> +  color: #323232;
color: #232323; на макете

2022-07-23 11:07 UTC, AlinaMalginova1998 commented on index.html
> +    <nav class="header__links-down">
Это тоже своего рода попап, который будет появляться при нажатии на кнопку "о проекте" (как я это понимаю). Поэтому нужно добавить модификатор, отвечающий за открытие этого попапа.

2022-07-24 07:54 UTC, AlinaMalginova1998 requested changes

2022-07-24 07:54 UTC, AlinaMalginova1998 commented on blocks/header/__links-down/header__links-down.css
>    align-items: flex-start;
У класса по-хорошему поставить нужно display: none, а у модификатора display: flex

2022-07-24 07:54 UTC, AlinaMalginova1998 commented on blocks/header/__links-down/_open/header__links-down_open.css
> +.header__links-down_open {
Данный файл не подключен в index.css

2022-07-24 08:17 UTC, Ser2204 commented on blocks/header/__links-down/header__links-down.css
>    align-items: flex-start;
свойства flex тоже перенес в модификатор

2022-07-24 08:18 UTC, Ser2204 commented on blocks/header/__links-down/_open/header__links-down_open.css
> +.header__links-down_open {
ок

2022-07-24 08:23 UTC, AlinaMalginova1998 approved these changes

2022-07-24 08:31 UTC, merged