Task 21 адаптив
yandex-practicum-14-8/projito_14_8 pull request #90
Opened 2022-07-24 00:42 UTC by iVANECHKA

Добавил только обводку у карточек в мобильной версии

2022-07-24 08:54 UTC, AlinaMalginova1998 requested changes
В мобильной версии заголовок должен быть не по центру, а слева 
![image](https://user-images.githubusercontent.com/39488063/180639830-79528594-bd4a-4711-a394-f7240107bce2.png)

2022-07-25 22:41 UTC, iVANECHKA commented
> В мобильной версии заголовок должен быть не по центру, а слева ![image](https://user-images.githubusercontent.com/39488063/180639830-79528594-bd4a-4711-a394-f7240107bce2.png)

2022-07-25 22:42 UTC, iVANECHKA commented
Заголовок слева, но только начиная с 360px включительно. Пришлось так сделать

2022-07-28 10:25 UTC, AlinaMalginova1998 approved these changes

2022-07-28 13:15 UTC, merged